### ISSUE TITLE
[Question] Is there any way to have it on build 419?

### ISSUE THREAD

**Issue by alvaro-canepa** [mplodowski/backupmanager-plugin#2]
I see the latest update, you post "**Laravel 5.5 or higher**", but is the only plugin to made backups. I need it for a production environment. 

Is not possible to have it in build 419 ?

Thanks

**Comment by mplodowski** [comment]
The only way I can think of is to buy plugin and contact me directly. I will check the purchase and then I can send you version 1.0.10.

This process will look like this:

1. Buy plugin from octobercms.com.
2. Send me email with purchase confirmation.
3. I will send you version 1.0.10.
4. Copy plugin files to `/plugins/renatio/backupmanager` folder.
5. Relog to backend area or use `plugin:refresh` command.
6. Freeze updates for this plugin.

**Comment by axomat** [comment]
I would like to take you up on your offer please for the pre-5.5 version. How can I contact you with my purchase details?

**Comment by mplodowski** [comment]
Send me following details:

- payment id
- payment date
- customer name

Email: michal.plodowski@gmail.com
