### ISSUE TITLE
Symfony error

### ISSUE THREAD

**Issue by devillom** [mplodowski/backupmanager-plugin#4]
`Symfony\Component\Debug\Exception\FatalThrowableError: Type error: Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::createDbDumpers() must be of the type array, null given, called in /home/c/cc07860/builders-steps.ru/public_html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php on line 14 in /home/c/cc07860/builders-steps.ru/public_html/plugins/renatio/backupmanager/vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php:25`

**Comment by mplodowski** [comment]
Go to plugin settings and reset settings to default. Then check if you have selected your database driver.
