### ISSUE TITLE
'Backups' menu item not showing after plugin installation.

### ISSUE THREAD

**Issue by drbiskit** [mplodowski/backupmanager-plugin#5]
Hi,

I have inherited an October site. I have no direct access to the server, only the CMS, and I need to migrate the site to a new server, so wanted to try your plugin.

I have connected the site to a new project, purchased and installed the Backup manager plugin from the October site. I can see that the plugin is included in the Update & plugins list. But there is no 'Backups' menu item appearing in the Backend, so I am not able to use it currently.

Are you able to suggest any possible causes for this, or actions to try? I'm expecting that this will be due to some sort of configuration that the original developer has put in place.

Also - Could you confirm what the url path *should* be for viewing the plugin page please.

NB: I have not used October before, so am still finding my way around.

Many thanks.

**Comment by mplodowski** [comment]
Hi,

this is probably caused by insufficient permissions. You must have permission to access this plugin or be super user.

The url is:

    backend/renatio/backupmanager/backups

If you see access denied page, than I don't think you can do something with it without database access or access to CMS roles/permissions.

**Comment by drbiskit** [comment]
Thanks - I don't currently have a super user account, so I expect this is the issue.
