### ISSUE TITLE
Error after update octobercms build 419 to 434

### ISSUE THREAD

**Issue by goeroe** [mplodowski/backupmanager-plugin#6]
Just updated a website from build 419 to build 434 and confirmed to update the plugin too. After updating I tried to manually create a backup and I'm getting the following error:
```
"Type error: Argument 1 passed to Spatie\Backup\Tasks\Backup\BackupJobFactory::createDbDumpers() must be of the type array, null given, called in ../vendor/spatie/laravel-backup/src/Tasks/Backup/backupJobFactory.php on line 14" on line 25 of ../vendor/spatie/laravel-backup/src/Tasks/Backup/BackupJobFactory.php
```

**Comment by mplodowski** [comment]
Go to plugin settings and reset settings to default. Then check if you have selected your database driver.
